import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Providers } from './providers/NextUIProvider';

import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-Poppins',
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Food Delivery Web App',
  description: 'Generated by Matveichuk Mikhail',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <Providers>
          <Header />
          <main className="w-full mt-[100px] px-[20px]">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
